enable-magisk-update = true
parallel-jobs = 1
rv-brand = ""

[Ruby-Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'GmsCore support'"
module-prop-name = "Ruby-Music"

[Ruby-YT]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Hide ads' 'Video ads' 'Downloads' 'Disable precise seeking gesture' 'Seekbar tapping' 'Swipe controls' 'Disable auto captions' 'Navigation buttons' 'Hide player overlay buttons' 'Hide endscreen cards' 'Disable fullscreen ambient mode' 'Hide info cards' 'Disable suggested video end screen' 'SponsorBlock' 'Theme' 'Remove background playback restrictions' 'Check watch history domain name resolution' 'Bypass URL redirects' 'Open links externally' 'Remove tracking query parameter' 'Spoof video streams' 'Remember video quality'"
exclusive-patches = true
module-prop-name = "Ruby-YT"
patcher-args = "-OiconPath=Icons "
