enable-magisk-update = true
parallel-jobs = 1
rv-brand = " "

[RubyYTM]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"

[RubyYT]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide ads' 'Video ads' 'Downloads' 'Seekbar' 'Swipe controls' 'Disable auto captions' 'Custom branding' 'Navigation buttons' 'Hide player overlay buttons' 'Hide end screen cards' 'Hide end screen suggested video' 'Disable fullscreen ambient mode' 'SponsorBlock' 'Remove background playback restrictions' 'Check watch history domain name resolution' 'GmsCore support' 'Bypass URL redirects' 'Open links externally' 'Remove tracking query parameter' 'Spoof video streams' 'Force original audio' 'Disable HDR video' 'Video quality'"
exclusive-patches = true
patcher-args = "-e 'Custom branding' -OappName=YouTube -OiconPath=/icons"




